# -*- coding: utf-8 -*-
"""homework3apln553.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAiw_naJcsZRr_3kDKH8fxOUwWh1cDSl
"""

git clone https://github.com/yourusername/text_tools_project.git

cd text_tools_project

echo -e "Song Authorship" >> README.md

vim README.md

git status

git add README.md

git commit -m "updated README.md"

cp /path/to/file ./text_tools_project/

git add filename
git commit -m "Added file for project"

git push origin master